[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
plethora = { path = "../.." }
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.38.0", features = ["full"] }
